name: Test Project
on: push   # when a new code pus, trigger the workflow.concurrency.concurrency: 
jobs:
    test:
        runs-on: ubuntu-latest #VM where all the steps were executed.
        steps:
            - name: Get the code
              uses: actions/checkout@v4  #[https://github.com/marketplace/actions/checkout]
            - name: Install NodeJs # before installing check the list of software installed on a selected image. 
              uses: actions/setup-node@v4
              with:
                node-version: 20 # [https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md]
            - name: Install depenedencies
              run: npm ci # same as npm install
            - name: Run tests
              run: npm test


             

